# Default config file

HelpDisplay:
    # Separator between pages
    subPageSeperator: '/'
    notFoundMessage: 'The specified page was not found'
    header:
        enabled: true
        text: ''
    footer:
        enabled: false
        text: ''

MySQL:
    username: 'user'
    password: 'password'
    host: 'localhost'
    port: 3306
    database: 'database'